set-option -g default-shell /bin/zsh
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# Extended keys: allows terminals to send modifiers on keys like Shift-Space
set -g extended-keys on
set -as terminal-features ',xterm-256color:extkeys'
